language: c
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq install gnome-common gtk-doc-tools libglib2.0-dev libgtk-3-dev libsoup2.4-dev libgirepository1.0-dev
- sudo apt-get -qq install python3-gi python3-cairo gir1.2-gtk-3.0 gir1.2-gdkpixbuf-2.0
before_script:
- ./autogen.sh
- ./configure --prefix /usr
script:
- make
- sudo make install
- /usr/bin/python3 -m unittest discover -v
